config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: 'users/sessions'
  }
  devise_for :companies
  devise_for :users

  scope module: :users do
  	resources :infos
  	resources :drafts, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:show, :index, :update, :destroy]
  	resources :helps
  	resources :comments, only: [:create]
  	resources :engineers, only: [:new, :show, :edit, :create, :update]
  	post   '/favorite/:info_id' => 'favorites#favorite',   as: 'favorite'
    delete '/favorite/:info_id' => 'favorites#unfavorite', as: 'unfavorite'
    post   '/follow/:engineer_id' => 'follows#follow',   as: 'follow'
    delete '/follow/:engineer_id' => 'follows#unfollow', as: 'unfollow'
    post   '/mark/:company_id' => 'marks#mark',   as: 'mark'
    delete '/mark/:company_id' => 'marks#unmark', as: 'unmark'
    resources :rooms, only: [:show, :create]
    get '/ranking' => 'infos#ranking', as: 'ranking'
    get '/withdraw/:id' => 'users#withdraw', as: 'withdraw'
    patch '/evolution/:id' => 'engineers#evolution', as: 'evolution'
    resources :boxes, only: [:show, :create, :destroy]
    resources :interviews, only: [:create, :destroy]
    get 'infos/tags/:tag', to: 'infos#index', as: :info_tag
    get 'helps/tags/:tag', to: 'helps#index', as: :help_tag
  end

  scope module: :companies do
  	resources :companies do
  		resources :company_payments, only: [:new, :create]
  	end
  	resources :engineers, only: [:index]
  	resources :jobs
  	resources :topics
  	resources :offers, only: [:new, :show, :create, :destroy]
  	get 'topics/tags/:tag', to: 'topics#index', as: :topic_tag
  	get 'jobs/tags/:tag', to: 'jobs#index', as: :job_tag
  end

  namespace :admins do
  	resources :admins, only: [:index, :show, :destroy]
  	resources :users, only: [:index, :update, :destroy]
  	resources :engineers, only: [:index, :update, :destroy]
  	resources :companies, only: [:index, :update, :destroy]
  	resources :company_payments, only: [:index, :destroy]
  end

  namespace :api, format: 'json' do
    get 'infos/preview'
  end

  root 'top#top'
  get 'top/about'
  get '/contact' => 'top#contact', as: 'contact'
  post '/contacting' => 'top#contacting', as: 'contacting'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord

	belongs_to :company

	validates :title, presence: true
	validates :body, presence: true

	acts_as_taggable
end

app/controllers/admins/companies_controller.rb
class Admins::CompaniesController < ApplicationController

	before_action :admin?

	def index
		@companies = Company.with_deleted.page(params[:page]).per(20).order("created_at DESC")
	end

	def update
		@company = Company.with_deleted.find(params[:id])
		if @company.restore
			flash[:notice] = "復活!!!!!!!!!!!!!!!!!!!!!!!!!!"
            redirect_to  admins_admins_path
        else
        	render :index
        end
	end

	def destroy
		@company = Company.find(params[:id])
		flash[:notice] = "削除!!!!!!!!!!!!!!!!!!!!!!!!!!"
		@company.destroy
		redirect_to  admins_admins_path
	end

	private

	def admin?
		unless admin_signed_in?
			redirect_to root_path
		end
	end
end

app/controllers/companies/companies_controller.rb
class Companies::CompaniesController < ApplicationController

	before_action :signed_in?
	before_action :deleted_company?, only: [:show]
	before_action :correct_company, only: [:edit ,:update]

	def show
		@company = Company.find(params[:id])
		@topics = @company.topics.page(params[:page]).per(10).order("created_at DESC")
		@jobs = @company.jobs.order("created_at DESC")
		@marks = @company.marks.order("created_at DESC")
		@offers = @company.offers.order("created_at DESC")
		@boxes = @company.boxes.order("created_at DESC")
	end

	def index
		@q = Company.ransack(params[:q])
        @companies = @q.result(distinct: true).page(params[:page]).per(10).order("created_at DESC")
		@offer = Offer.new
	end

	def edit
		@company = Company.find(params[:id])
	end

	def update
		@company = Company.find(params[:id])
		if @company.update(company_params)
			redirect_to company_path(current_company.id)
		else
			render :edit
		end
	end


	private

	def company_params
		params.require(:company).permit(:surname, :name, :company_image, :introduction)
	end

	def signed_in?
        unless user_signed_in? or company_signed_in?
            redirect_to root_path
        end
    end

    def deleted_company?
    	unless Company.with_deleted.find(params[:id]).deleted_at.nil?
            flash[:alert] = "no user!!!!!!!!"
            redirect_to users_path
        end
    end

	def correct_company
        @company = Company.find(params[:id])
        if user_signed_in? or current_company != @company
            redirect_to users_path
        end
    end
end

app/controllers/companies/company_payments_controller.rb
class Companies::CompanyPaymentsController < ApplicationController

    before_action :authenticate_company!
    before_action :company_paymented

	def new
		@company_payment = CompanyPayment.new
	end

    def create
		@company = current_company
	    @company_payment = @company.company_payments.build(company_payment_params)

	    @company.with_lock do
	      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
	      amount = 1200000
	      charge = Payjp::Charge.create(currency: 'jpy', amount: amount, card: params['payjp-token'])
	      @company_payment.charge_id = charge['id']
	      @company_payment.company_id = current_company.id

	      respond_to do |format|
	        if @company_payment.save
	          format.html { redirect_to company_path(@company) }
	          flash[:notice] = '購入しました。'
	        end
	      end
	    end
	    rescue Payjp::CardError
	      respond_to do |format|
	          format.html { redirect_to company_path(@company) }
	          flash[:notice] = 'カードエラーが発生しました'
	    end
	end

  private

    def company_payment_params
      params.require(:company_payment).permit(:name)
    end

    def company_paymented
    	if current_company.company_payments.exists?
    		redirect_to company_path(current_company.id)
    	end
    end


end

app/controllers/companies/confirmations_controller.rb
# frozen_string_literal: true

class Companies::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/companies/engineers_controller.rb
class Companies::EngineersController < ApplicationController

    before_action :signed_in?

	def index
		if params[:q] != nil
            params[:q]['user_name_or_surname_or_name_or_age_or_introduction_or_languages_language_cont_any'] = params[:q]['user_name_or_surname_or_name_or_age_or_introduction_or_languages_language_cont_any'].split(/[\p{blank}\s]+/)
            @q = Engineer.ransack(params[:q])
            @engineers = @q.result(distinct: true).page(params[:page]).per(10).order("created_at DESC")
        else
            @q = Engineer.ransack(params[:q])
            @engineers = Engineer.page(params[:page]).per(10).order("created_at DESC")
        end
		@offer = Offer.new
	end

    private

    def signed_in?
        unless user_signed_in? or company_signed_in?
            redirect_to root_path
        end
    end
end

app/controllers/companies/jobs_controller.rb
class Companies::JobsController < ApplicationController

    before_action :signed_in?
    before_action :authenticate_company!, only: [:new, :create]
	before_action :correct_company, only: [:edit, :update, :destroy]
	before_action :company_paymented?, only: [:new, :create, :edit, :update]

	def new
		@job = Job.new
	end

	def show
		@job = Job.find(params[:id])
	end

	def index
		if params[:tag]
	        @jobs = Job.tagged_with(params[:tag]).page(params[:page]).per(10).order("created_at DESC")
	        @q = Job.ransack(params[:q])
		elsif params[:q] != nil
            params[:q]['title_or_status_or_salary_or_job_or_tags_name_cont_any'] = params[:q]['title_or_status_or_salary_or_job_or_tags_name_cont_any'].split(/[\p{blank}\s]+/)
            @q = Job.ransack(params[:q])
            @jobs = @q.result(distinct: true).page(params[:page]).per(10).order("created_at DESC")
        else
            @q = Job.ransack(params[:q])
            @jobs = Job.page(params[:page]).per(10).order("created_at DESC")
        end
	end

	def edit
	end

	def create
		@job = Job.new(job_params)
		@job.company_id = current_company.id
		if @job.save
			redirect_to job_path(@job)
			flash[:notice] = "求人登録が完了しました！"
		else
			render :new
		end
	end

	def update
		if @job.update(job_params)
			flash[:notice] = "求人情報を更新しました！"
			redirect_to job_path(@job)
		else
			render :edit
		end
	end

	def destroy
		@job.destroy
		redirect_to engineers_path
	end

	private

	def job_params
		params.require(:job).permit(:company_id, :job_image, :title, :job, :salary, :status, :tag_list)
	end

	def signed_in?
        unless user_signed_in? or company_signed_in?
            redirect_to root_path
        end
    end

	def correct_company
        @job = Job.find(params[:id])
        if user_signed_in? or current_company != @job.company
            redirect_to users_path
        end
    end

    def company_paymented?
    	unless current_company.company_payments.exists?
    		redirect_to new_company_company_payment_path(current_company.id)
    	end
    end

end

app/controllers/companies/offers_controller.rb
class Companies::OffersController < ApplicationController

    before_action :signed_in?
    before_action :authenticate_company!, only: [:create]
    before_action :correct_company, only: [:destroy]
    before_action :company_paymented?, only: [:create]

    def show
        @offer = Offer.find(params[:id])
        @box = Box.new
        if user_signed_in?
            unless @offer.engineer_id == current_user.id
                redirect_to user_path(current_user.id)
            end
        end
    end

    def create
        @offer = Offer.new(offer_params)
        @offer.company_id = current_company.id
        if Offer.where(engineer_id: @offer.engineer_id, company_id: current_company.id).exists?
            flash[:notice] = "すでにオファーしています！"
            redirect_to engineer_path(@offer.engineer_id)
        else
            if @offer.save!
                flash[:notice] = "オファーを送信しました！"
                redirect_to offer_path(@offer)
            else
                @engineers = Engineer.where(offer: 1)
                @offer = Offer.new
                render template: "companies/engineers/index"
            end
        end
    end

    def destroy
        @offer = Offer.find(params[:id])
        @offer.destroy
        redirect_to company_path(current_company.id)
    end

    private

    def offer_params
    	params.require(:offer).permit(:company_id, :engineer_id, :title, :job, :status, :salary)
    end

    def signed_in?
        unless user_signed_in? or company_signed_in?
            redirect_to root_path
        end
    end

    def correct_company
        @offer = Offer.find(params[:id])
        if user_signed_in? or current_company != @offer.company
            redirect_to users_path
        end
    end
    def company_paymented?
        unless current_company.company_payments.exists?
            redirect_to new_company_company_payment_path(current_company.id)
        end
    end
end

app/controllers/companies/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Companies::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/companies/passwords_controller.rb
# frozen_string_literal: true

class Companies::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/companies/registrations_controller.rb
# frozen_string_literal: true

class Companies::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies/sessions_controller.rb
# frozen_string_literal: true

class Companies::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/companies/topics_controller.rb
class Companies::TopicsController < ApplicationController

    before_action :signed_in?
	before_action :correct_company, only: [:edit, :update, :destroy]

	def new
		@topic = Topic.new
	end

	def show
		@topic = Topic.find(params[:id])
	end

	def index
		if params[:tag]
	        @topics = Topic.tagged_with(params[:tag]).page(params[:page]).per(10).order("created_at DESC")
	        @q_topic = Topic.ransack(params[:q])
		elsif params[:q] != nil
            params[:q]['title_or_body_or_tags_name_cont_any'] = params[:q]['title_or_body_or_tags_name_cont_any'].split(/[\p{blank}\s]+/)
            @q_topic = Topic.ransack(params[:q])
            @topics = @q_topic.result(distinct: true).page(params[:page]).per(10).order("created_at DESC")
        else
            @q_topic = Topic.ransack(params[:q])
            @topics = Topic.page(params[:page]).per(10).order("created_at DESC")
        end
        render :index
	end

	def edit
	end

	def create
		@topic = Topic.new(topic_params)
		@topic.company_id = current_company.id
		if @topic.save
			flash[:notice] = "トピックの投稿が完了しました！"
			redirect_to topic_path(@topic)
		else

			render :new
		end
	end

	def update
		if @topic.update(topic_params)
			flash[:notice] = "トピックの更新が完了しました！"
			redirect_to topic_path(@topic)
		else
			render :edit
		end
	end

	def destroy
		@topic = Topic.find(params[:id])
		@topic.destroy
		redirect_to engineers_path
	end

	private

	def topic_params
		params.require(:topic).permit(:company_id, :title, :body, :tag_list)
	end

	def signed_in?
        unless user_signed_in? or company_signed_in?
            redirect_to root_path
        end
    end

	def correct_company
        @topic = Topic.find(params[:id])
        if user_signed_in? or current_company.id != @topic.company_id
            redirect_to topics_path
        end
    end
end

app/helpers/admins/companies_helper.rb
module Admins::CompaniesHelper
end

app/helpers/companies/companies_helper.rb
module Companies::CompaniesHelper
end

app/helpers/companies/company_payments_helper.rb
module Companies::CompanyPaymentsHelper
end

app/helpers/companies/engineers_helper.rb
module Companies::EngineersHelper
end

app/helpers/companies/jobs_helper.rb
module Companies::JobsHelper
end

app/views/companies/topics/_topics.html.erb
<% if topics.exists? %>

<table class="table table-sm">

	<% topics.each do |t| %>

    <tr class="row">
		<td class="col-md-1"><%= attachment_image_tag t.company, :company_image, fallback: "no_image.jpg", size:"60x60" %></td>
		<td class="col-md-10">
			<div class="info_created_at">
				<%= link_to company_path(t.company) do %>
			    	<%= t.company.company_name %>
			    <% end %>
			        が<%= t.created_at.strftime('%Y/%m/%d') %>に登録
			</div>
			<%= link_to topic_path(t) do %>
			  <div class="index-title">
			    <%= t.title %>
			  </div>
			<% end %>
			<div class="info_created_at">
		        <% t.tag_list.each do |tag| %>
                    <%= link_to topic_tag_path(tag) do %>
                        <code><%= tag %></code>
                    <% end %>
                <% end %>
		    </div>
		</td>
		<td class="col-md-1">
			<% if t.company == current_company %>
	            <%= link_to "編集", edit_topic_path(t) %>
	        <% end %>
	    </td>
	</tr>
	<% end %>
</table>
<%= paginate topics %>


<% else %>

	<div class="toping">
	    <h5 class="toping gocenter">There are no topics</h5>
	</div>

<% end %>

app/views/companies/topics/edit.html.erb
<div class="container_info toping">

<%= form_for @topic, url: topic_path , method: :patch do |f| %>

<%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
  	<%= f.text_field :title, placeholder: "タイトル (サイズは、見出し 1)" %>
  	<%= f.text_field :tag_list, placeholder: "プログラミング技術に関連するタグ(スペースで区切る)" %>
  </div>
  <div class="form-group">

		<%= f.text_area :body, placeholder: "本文", :size => "80x50", 'data-provider': :summernote, src: "./js/summernote/lang/summernote-ja-JP.js" %>
  </div>

  <div class="form-group row">
  	<div class="col-md-2 offset-md-10">
  		<%= f.submit "投稿する", class: "btn btn-success" %>
  	</div>
  </div>

<% end %>
</div>

app/views/companies/topics/index.html.erb
<div class="container">

    <div class="row">

        <div class="col-2 toping sideright">
            <%= render 'layouts/sidebar' %>
        </div>

        <div class="col-10 whiting toping">


            <%= search_form_for @q_topic, url:topics_path, remote: true do |f| %>

                <div class="search_field">
                    <%= f.text_field :title_or_body_or_tags_name_cont_any %>
                    <%= button_tag :type => "submit", class: "btn btn-default btn-s-md s-button" do %>
                        <i class="fa fa-search"></i>
                    <% end %>
                </div>
            <% end %>

            <div class='topic toping container'>
                <%= render 'companies/topics/topics', topics: @topics %>
            </div>

        </div>
    </div>
</div>

app/views/companies/topics/new.html.erb
<div class="container_info toping showtime">

<%= form_for @topic, url: topics_path , method: :post do |f| %>

<%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
  	<%= f.text_field :title, placeholder: "タイトル (サイズは、見出し 1)" %>
  	<%= f.text_field :tag_list, placeholder: "プログラミング技術に関連するタグ(スペースで区切る)" %>
  </div>
  <div class="form-group">

		<%= f.text_area :body, placeholder: "本文", :size => "80x50", 'data-provider': :summernote, src: "./js/summernote/lang/summernote-ja-JP.js" %>
  </div>

  <div class="form-group row">
  	<div class="col-md-2 offset-md-10">
  		<%= f.submit "投稿する", class: "btn btn-success" %>
  	</div>
  </div>

<% end %>
</div>

app/views/companies/topics/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="container toping showtime">

    <div class="row">
		<div class="col-1">
			<%= attachment_image_tag @topic.company, :company_image, fallback: "no_image.jpg", size: "60X60"%>
		</div>
		<div class="col-7">
			<%= link_to company_path(@topic.company) do %>
		    	<%= @topic.company.company_name %>
		    <% end %>
		</div>
		<div class="col-3">
		    <div class="info_created_at">
				<%= @topic.created_at.strftime('%Y/%m/%d') %>に投稿
			</div>
        </div>
	</div>
    <div class="show_title">
	    <%= @topic.title %>
	</div>

    <div class="row">
    	<div class="col-7 offset-2">
	    	<% @topic.tag_list.each do |tag| %>
                <%= link_to topic_tag_path(tag) do %>
                    <code><%= tag %></code>
                <% end %>
            <% end %>
		</div>
		<div class="col-3">
			<% if company_signed_in? %>
		    <% if @topic.company_id == current_company.id %>

		        <p><%= link_to "この記事を編集する", edit_topic_path(@topic) %></p>
		        <p><%= link_to "この記事を削除する", topic_path(@topic), method: :delete, "data-confirm" => "本当に削除しますか？" %></p>

		    <% end %>
		    <% end %>
		</div>
	</div>

    <%= @topic.body.html_safe %>

</div>