config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: 'users/sessions'
  }
  devise_for :companies
  devise_for :users

  scope module: :users do
  	resources :infos
  	resources :drafts, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:show, :index, :update, :destroy]
  	resources :helps
  	resources :comments, only: [:create]
  	resources :engineers, only: [:new, :show, :edit, :create, :update]
  	post   '/favorite/:info_id' => 'favorites#favorite',   as: 'favorite'
    delete '/favorite/:info_id' => 'favorites#unfavorite', as: 'unfavorite'
    post   '/follow/:engineer_id' => 'follows#follow',   as: 'follow'
    delete '/follow/:engineer_id' => 'follows#unfollow', as: 'unfollow'
    post   '/mark/:company_id' => 'marks#mark',   as: 'mark'
    delete '/mark/:company_id' => 'marks#unmark', as: 'unmark'
    resources :rooms, only: [:show, :create]
    get '/ranking' => 'infos#ranking', as: 'ranking'
    get '/withdraw/:id' => 'users#withdraw', as: 'withdraw'
    patch '/evolution/:id' => 'engineers#evolution', as: 'evolution'
    resources :boxes, only: [:show, :create, :destroy]
    resources :interviews, only: [:create, :destroy]
    get 'infos/tags/:tag', to: 'infos#index', as: :info_tag
    get 'helps/tags/:tag', to: 'helps#index', as: :help_tag
  end

  scope module: :companies do
  	resources :companies do
  		resources :company_payments, only: [:new, :create]
  	end
  	resources :engineers, only: [:index]
  	resources :jobs
  	resources :topics
  	resources :offers, only: [:new, :show, :create, :destroy]
  	get 'topics/tags/:tag', to: 'topics#index', as: :topic_tag
  	get 'jobs/tags/:tag', to: 'jobs#index', as: :job_tag
  end

  namespace :admins do
  	resources :admins, only: [:index, :show, :destroy]
  	resources :users, only: [:index, :update, :destroy]
  	resources :engineers, only: [:index, :update, :destroy]
  	resources :companies, only: [:index, :update, :destroy]
  	resources :company_payments, only: [:index, :destroy]
  end

  namespace :api, format: 'json' do
    get 'infos/preview'
  end

  root 'top#top'
  get 'top/about'
  get '/contact' => 'top#contact', as: 'contact'
  post '/contacting' => 'top#contacting', as: 'contacting'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins/engineers_controller.rb
class Admins::EngineersController < ApplicationController

	before_action :admin?

	def index
		@engineers = Engineer.with_deleted.page(params[:page]).per(20).order("created_at DESC")
	end

	def update
		@engineer =  Engineer.only_deleted.find(params[:id])
		if @engineer.restore
			flash[:notice] = "復活!!!!!!!!!!!!!!!!!!!!!!!!!!"
	        redirect_to  admins_admins_path
	    else
	    	render :index
	    end
	end

	def destroy
		@engineer = Engineer.find(params[:id])
		@engineer.destroy
		redirect_to  admins_admins_path
	end

	private

	def admin?
		unless admin_signed_in?
			redirect_to root_path
		end
	end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

	before_action :admin?

	def index
		@users = User.with_deleted.page(params[:page]).per(20)
	end

	def update
		@user =  User.with_deleted.find(params[:id])
		if @user.restore
			flash[:notice] = "復活!!!!!!!!!!!!!!!!!!!!!!!!!!"
            redirect_to  admins_admins_path
        else
        	render :index
        end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:notice] = "復活!!!!!!!!!!!!!!!!!!!!!!!!!!"
		redirect_to  admins_admins_path
	end

	private

	def admin?
		unless admin_signed_in?
			redirect_to root_path
		end
	end
end

app/controllers/companies/engineers_controller.rb
class Companies::EngineersController < ApplicationController

    before_action :signed_in?

	def index
		if params[:q] != nil
            params[:q]['user_name_or_surname_or_name_or_age_or_introduction_or_languages_language_cont_any'] = params[:q]['user_name_or_surname_or_name_or_age_or_introduction_or_languages_language_cont_any'].split(/[\p{blank}\s]+/)
            @q = Engineer.ransack(params[:q])
            @engineers = @q.result(distinct: true).page(params[:page]).per(10).order("created_at DESC")
        else
            @q = Engineer.ransack(params[:q])
            @engineers = Engineer.page(params[:page]).per(10).order("created_at DESC")
        end
		@offer = Offer.new
	end

    private

    def signed_in?
        unless user_signed_in? or company_signed_in?
            redirect_to root_path
        end
    end
end

app/controllers/users/boxes_controller.rb
class Users::BoxesController < ApplicationController

    before_action :authenticate_user!, only: [:create]
    before_action :correct_user, only: [:show, :destroy]

	def show
		@box = Box.find(params[:id])
		@engineer = Engineer.find_by(id: @box.engineer_id)
		@company = Company.find_by(id: @box.company_id)
		@interview = Interview.new
		@interviews = @box.interviews
	end

	def create
		@box = Box.new(box_params)
		@box.save
		redirect_to box_path(@box)
	end

	def destroy
		@box = Box.find(params[:id])
		@box.destroy
		redirect_to engineer_path(current_user.id)
	end

	private

	def box_params
		params.require(:box).permit(:company_id, :engineer_id)
	end

	def correct_user
        @box = Box.find(params[:id])
        if user_signed_in?
	        if current_user.id != @box.engineer_id
	            redirect_to infos_path
	        end
	    elsif company_signed_in?
	    	if current_company.id != @box.company_id
	            redirect_to engineers_path
	        end
	    else
	    	redirect_to root_path
	    end
    end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController

    before_action :authenticate_user!

	def create
        @comment = Comment.new(comment_params)
        @help = @comment.help
        @comments = Comment.where(help_id: @help.id)
        @comment.user_id = current_user.id
        if @comment.save
            @comment = Comment.new
            # render :create
        end
    end

    private

    def comment_params
    	params.require(:comment).permit(:user_id, :help_id, :comment)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/drafts_controller.rb
class Users::DraftsController < ApplicationController

    before_action :authenticate_user!, only: [:index, :edit, :update, :destroy]
	before_action :correct_user, only: [:edit, :update, :destroy]

	def index
		@engineer = Engineer.find_by(id: current_user.id)
		@drafts = @engineer.drafts.page(params[:page]).per(10).order("created_at DESC")
	end

	def edit
	end

	def update
		if params[:commit] == "投稿する"
			@info = Info.new(draft_params)
			@info.engineer_id = current_user.id
			if @info.save
				@draft.destroy
				flash[:notice] = "記事の投稿が完了しました！"
				redirect_to info_path(@info)
			else
				render :edit
			end
		else
			if @draft.update(draft_params)
				flash[:notice] = "下書き保存しました！"
				redirect_to engineer_path(current_user.id)
			else
				render :edit
			end
		end
	end

	def destroy
		@draft.destroy
		redirect_to drafts_path
	end

	private

	def draft_params
		params.require(:draft).permit(:engineer_id, :title, :body, :tag_list)
	end

	def correct_user
        @draft = Draft.find(params[:id])
        if current_user.id != @draft.engineer_id
            redirect_to infos_path
        end
    end

end

app/controllers/users/engineers_controller.rb
class Users::EngineersController < ApplicationController

    before_action :authenticate_user!, only: [:new,:edit,:create,:update,:evolution,:destroy]
    before_action :signed_in?, only: [:show]
    before_action :correct_user, only: [:edit, :update, :evolution, :destroy]
    before_action :already_agent, only: [:new, :create]

	def new
		@engineer = Engineer.new
	end

	def show
		@engineer = Engineer.find(params[:id])
        @languages = @engineer.languages
        @marks = @engineer.marks.page(params[:page]).per(10).order("created_at DESC")
        @offers = @engineer.offers.page(params[:page]).per(10).order("created_at DESC")
        @boxes = @engineer.boxes.page(params[:page]).per(10).order("created_at DESC")
        @offer = Offer.new

        if params[:q] != nil
            params[:q]['title_or_body_or_language_cont_any'] = params[:q]['title_or_body_or_language_cont_any'].split(/[\p{blank}\s]+/)
            @q_info = Info.ransack(params[:q])
            info = @q_info.result(distinct: true)
            @infos = @engineer.info.page(params[:page]).per(10).order("created_at DESC")
        else
            @q_info = Info.ransack(params[:q])
            @infos = @engineer.infos.page(params[:page]).per(10).order("created_at DESC")
        end

        if user_signed_in?
            @user = User.find(params[:id])
            @currentUserEntry = Entry.where(user_id: current_user.id)
            @userEntry=Entry.where(user_id: @user.id)
            unless @user.id == current_user.id
                @currentUserEntry.each do |cu|
                    @userEntry.each do |u|
                    if cu.room_id == u.room_id then
                        @isRoom = true
                        @roomId = cu.room_id
                    end
                    end
                end
            end
            unless @isRoom
                @room = Room.new
                @entry = Entry.new
            end
        end
	end

    def edit
    end

    def create
    	@engineer = Engineer.new(engineer_params)
        @engineer.user_id = current_user.id
        @engineer.id = current_user.id
    	if @engineer.save
            flash[:notice] = "Agent登録 完了!!！"
    		redirect_to engineer_path(current_user.id)
    	else
    		render :new
    	end
    end

    def update
    	if @engineer.update(engineer_params)
            flash[:notice] = "Agent情報の更新 完了!!！"
    		redirect_to engineer_path(current_user.id)
    	else
    		render :edit
    	end
    end

    def evolution
        x = 0
        @infos = @engineer.infos
        @infos.each do |i|
            x = x + i.favorites.count
        end
        x = x * 3
        y = @engineer.follows_count.to_i * 2
        x = x + y
        current_user.comments do |c|
            x = x + 1
        end
        if x > 500
            @engineer.update(rank: 8)
            redirect_to engineer_path(current_user.id)
        elsif x > 300
            @engineer.update(rank: 7)
            redirect_to engineer_path(current_user.id)
        elsif x > 200
            @engineer.update(rank: 6)
            redirect_to engineer_path(current_user.id)
        elsif x > 100
            @engineer.update(rank: 5)
            redirect_to engineer_path(current_user.id)
        elsif x > 50
            @engineer.update(rank: 4)
            redirect_to engineer_path(current_user.id)
        elsif x > 30
            @engineer.update(rank: 3)
            redirect_to engineer_path(current_user.id)
        elsif x > 10
            @engineer.update(rank: 2)
            redirect_to engineer_path(current_user.id)
        else
            @engineer.update(rank: 1)
            redirect_to engineer_path(current_user.id)
        end
    end

    private

    def engineer_params
    	params.require(:engineer).permit(:user_id, :surname, :name, :age, :profile_image, :introduction, :rank, :offer,
                                        languages_attributes: [:id, :language ,:experience_year, :description, :done, :_destroy,
                                        performances_attributes: [:id, :performance, :description, :_destroy]])
    end

    def signed_in?
        unless user_signed_in? or company_signed_in?
            redirect_to root_path
        end
        unless Engineer.with_deleted.find(params[:id]).deleted_at.nil?
            flash[:alert] = "no user!!!!!!!!"
            redirect_to infos_path
        end
    end

    def correct_user
        @engineer = Engineer.find(params[:id])
        if current_user != @engineer.user
            redirect_to infos_path
        end
    end

    def already_agent
        if Engineer.where(id: current_user.id).exists?
            flash[:notice] = "すでにAgent登録しています"
            redirect_to engineer_path(current_user.id)
        end
    end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController

    before_action :authenticate_user!
	before_action :set_variables

    def favorite
        favorite = current_user.favorites.new(info_id: @info.id)
        favorite.save
    end

    def unfavorite
        favorite = current_user.favorites.find_by(info_id: @info.id)
        favorite.destroy
    end

    private

    def set_variables
        @info = Info.find(params[:info_id])
        @id_name = "#favorite-link-#{@info.id}"
    end

end

app/controllers/users/follows_controller.rb
class Users::FollowsController < ApplicationController

	before_action :authenticate_user!
	before_action :set_variables

	def follow
		follow = current_user.follows.new(engineer_id: @engineer.id)
		follow.save
	end

	def unfollow
		follow = current_user.follows.find_by(engineer_id: @engineer.id)
		follow.destroy
	end

	private

	def set_variables
		@engineer = Engineer.find(params[:engineer_id])
		@id_name = "#follow-link-#{@engineer.id}"
    end
end

app/controllers/users/helps_controller.rb
class Users::HelpsController < ApplicationController

    before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
	before_action :signed_in?, only: [:show]
	before_action :correct_user, only: [:edit, :update, :destroy]

	def new
		@help = Help.new
	end

	def show
		@help = Help.find(params[:id])
		@comment = Comment.new
		@comments = Comment.where(help_id: @help.id)
	end

	def index
		if params[:tag]
	        @helps = Help.tagged_with(params[:tag]).page(params[:page]).per(10).order("created_at DESC")
	        @q_help = Help.ransack(params[:q])
		elsif params[:q] != nil
            params[:q]['title_or_body_or_tags_name_cont_any'] = params[:q]['title_or_body_or_tags_name_cont_any'].split(/[\p{blank}\s]+/)
            @q_help = Help.ransack(params[:q])
            @helps = @q_help.result(distinct: true).page(params[:page]).per(10).order("created_at DESC")
        else
            @q_help = Help.ransack(params[:q])
            @helps = Help.page(params[:page]).per(10).order("created_at DESC")
        end
        render :index
	end

	def edit
	end

	def create
		@help = Help.new(help_params)
		@help.user_id = current_user.id
		if @help.save
			flash[:notice] = "ヘルプの投稿が完了しました！"
			redirect_to help_path(@help)
		else
			render :new
		end
	end

	def update
		if @help.update(help_params)
			flash[:notice] = "ヘルプ情報の更新が完了しました！"
			redirect_to help_path(@help)
		else
			render :edit
		end
	end

	def destroy
		@help.destroy
		redirect_to helps_path
	end

	private

	def help_params
		params.require(:help).permit(:user_id, :title, :body, :tag_list)
	end

	def signed_in?
        unless user_signed_in? or company_signed_in?
            redirect_to root_path
        end
    end

	def correct_user
        @help = Help.find(params[:id])
        if current_user != @help.user
            redirect_to helps_path
        end
    end
end

app/controllers/users/interviews_controller.rb
class Users::InterviewsController < ApplicationController

    before_action :signed_in?

	def create
        @interview = Interview.new(interview_params)
        @box = @interview.box
        @interviews = Interview.where(box_id: @box.id)
        if @interview.save
            @interview = Interview.new
            redirect_to box_path(@box.id)
        end
    end

    def destroy
        @interview = Interview.find(params[:id])
        @interview.destroy
        redirect_to box_path(@interview.box_id)
    end

    private

    def interview_params
    	params.require(:interview).permit(:box_id, :message, :name)
    end

    def signed_in?
        unless user_signed_in? or company_signed_in?
            redirect_to root_path
        end
    end
end

app/controllers/users/marks_controller.rb
class Users::MarksController < ApplicationController

    before_action :authenticate_user!
	before_action :set_variables

    def mark
        mark = Engineer.find_by(id: current_user.id).marks.new(company_id: @company.id)
        mark.save
    end

    def unmark
        mark = Engineer.find_by(id: current_user.id).marks.find_by(company_id: @company.id)
        mark.destroy
    end

    private

    def set_variables
        @company = Company.find(params[:company_id])
        @id_name = "#mark-link-#{@company.id}"
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/views/users/engineers/_follow.html.erb
<%= render 'users/follows/follow', engineer: engineer %>

app/views/users/engineers/_form.html.erb
  <div id="language">
    <%= f.label :プログラミングの経験, class: "font-weight-normal" %><br>
    <%= f.fields_for :languages do |language| %>
      <%= render 'language_fields', f: language %>
    <% end %>
    <div id="links">
      <%= link_to_add_association '開発経験のある言語を追加する',f, :languages %>
    </div>
  </div>

app/views/users/engineers/_language_fields.html.erb
<div class="nested-fields well well-compact">
  <div class="form-group row">
    <div class="col-md-5">
      <%= f.text_field :language , placeholder:" 開発経験のある言語"%>
    </div>
    <div class="col-md-4">
      <%= f.number_field :experience_year, placeholder:"開発・経験", class: "col-md-7" %>年(未満)
    </div>

      <%= link_to_remove_association "削す", f %>

  </div>
  <div class="form-group row">
    <%= f.fields_for :performances do |performance| %>
      <%= render 'performance_fields', f: performance %>
    <%end%>
    <%= link_to_add_association "実績を追加する", f, :performances, class: "offset-md-1" %>
  </div>
</div>

app/views/users/engineers/_performance_fields.html.erb
<div class="nested-fields form-inline">
    <div class="col-md-10">
        <%= f.text_area :performance, placeholder:" 開発・経験内容など", class: "col-md-12", size: "100x5" %>
    </div>
    <div class="col-md-2">
        <%= link_to_remove_association "削す", f %>
    </div>
</div>

app/views/users/engineers/_skill.html.erb
<% if languages.exists? %>

<table class="table table-hover table-sm">

    <% languages.each do |l| %>

		<tr>
			<td><p><%= l.language %></p></td>
			<td><p><%= l.experience_year %>年</p></td>
	        <td>
	            <% l.performances.each do |pe| %>
			    <%= simple_format(pe.performance) %>
			    <% end %>
			</td>
		</tr>

	<% end %>
</table>

<% else %>

	<div class="toping">
	    <h5 class="toping gocenter">There are no skills</h5>
	</div>

<% end %>

app/views/users/engineers/edit.html.erb
<div class="container clearfix toping whiting">


    <%= form_for @engineer, url: engineer_path(@engineer), method: :patch do |f| %>

    <%= render 'layouts/error_messages', model: f.object %>

    <div class="row">

      <div class="col-md-4">
        <div class="form-group">
          <%= attachment_image_tag @engineer, :profile_image, fallback: "no_image.jpg", size:"250x250" %>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        </div>

        <div class="form-group row">
          <div class="col-md-6">
            <%= f.label :姓 %><br />
            <%= f.text_field :surname, class: "col-md-12" %>
          </div>
          <div class="col-md-6">
            <%= f.label :名 %><br />
            <%= f.text_field :name, class: "col-md-12" %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-md-5">
            <%= f.label :年齢 %><br />
            <%= f.number_field :age, placeholder:" 20",min: 1, max:100, class: "col-md-8" %>歳
          </div>
          <div class="col-md-7">
            <%= f.label :オファー %><br />
            <%= f.select :offer, Engineer.offers.keys.to_a, include_blank: "選択して下さい" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.submit "更新する", class: "btn-lg btn-primary col-md-5" %>
        </div>
      </div>

      <div class="col-md-7 offset-md-1">
        <div class="form-group">
          <%= f.label :自己紹介文 %><br />
          <%= f.text_area :introduction, class: "col-md-12"%>
        </div>
          <%= render 'form', f: f %>
          <%= f.hidden_field :rank, value: "駆け出しのAgent" %>

      </div>
    <% end %>
</div>
</div>

app/views/users/engineers/new.html.erb
<div class="container clearfix toping whiting">


    <%= form_for @engineer, url: engineers_path, method: :post do |f| %>

    <%= render 'layouts/error_messages', model: f.object %>

    <div class="row">

      <div class="col-md-4">
        <div class="form-group">
          <%= attachment_image_tag @engineer, :profile_image, fallback: "no_image.jpg", size:"200x200" %>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        </div>

        <div class="form-group row">
          <div class="col-md-6">
            <%= f.text_field :surname, placeholder:" 姓", class: "col-md-12" %>
          </div>
          <div class="col-md-6">
            <%= f.text_field :name, placeholder:" 名", class: "col-md-12" %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-md-5">
            <%= f.number_field :age, placeholder:" 20",min: 1, max:100, class: "col-md-8" %>歳
          </div>
          <div class="col-md-7">
            <%= f.select :offer, Engineer.offers.keys.to_a, include_blank: "選択して下さい" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.submit "登録する", class: "btn-lg btn-primary"  %>
        </div>
      </div>

      <div class="col-md-8 lefting">
        <div class="form-group">
          <%= f.text_area :introduction, placeholder:" 自己紹介文", class: "col-md-12"%>
        </div>
          <%= render 'form', f: f %>
          <%= f.hidden_field :rank, value: "駆け出しのAgent" %>
      </div>
    <% end %>
</div>
</div>

app/views/users/engineers/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="container whiting">
<div class="toping">
<div class="row">

  <div class="col-md-3">

	<table class="table">

        <%= attachment_image_tag @engineer, :profile_image, fallback: "no_image.jpg", size:"255x255" %>

	    <% if user_signed_in? %>
		    <% if @engineer.id == current_user.id %>
		        <tr>
		            <th class="username">
		            	<%= link_to user_path(@engineer.id) do %>
							<%= @engineer.user.name %>
						<% end %>
		  			</th>
	            </tr>
	            <tr>
	            	<th class="user_fullname"><%= @engineer.surname %><%= @engineer.name %> 様</th>
            	</tr>
            	<tr>
		            <th><div class="draft_link col-4 offset-8">
		            	<%= link_to "下書き", drafts_path %>
		            </div></th>
	            </tr>
		    <% else %>
		        <tr>
		            <th>
		            	<%= link_to user_path(@engineer.id) do %>
							<%= @engineer.user.name %>
						<% end %>
	            	</th>
	            </tr>
			    <tr>
			        <th><%= render 'users/engineers/follow', engineer: @engineer %></th>
			    </tr>
			<% end %>
	    <% elsif company_signed_in? && @engineer.offer == "受け取る" %>
	        <tr>
	            <th><%= @engineer.surname %><%= @engineer.name %> 様</th>
            </tr>
	        <tr>
	            <th><%= @engineer.age %> 歳</th>
	        </tr>
	        <tr>
		      <th><%= render 'companies/offers/new_offer', offer: @offer, engineer: @engineer %></th>
		    </tr>
		<% else %>
		    <tr>
	            <th>オファーを許可していません</th>
            </tr>
	    <% end %>

        <% if user_signed_in? %>
		  <% unless @engineer.id == current_user.id %>
			<% if @isRoom == true %>
			  <%= link_to "チャットへGo!", room_path(@roomId) %>
			<% else %>
			  <%= form_for @room do |f| %>
			    <%= fields_for @entry do |e| %>
			      <%= e.hidden_field :user_id, :value=> @user.id %>
			    <% end %>
			    <%= f.submit "チャットを始める" %>
			  <% end %>
			<% end %>
		  <% end %>
		<% end %>

		<tr>
	        <th><% if @engineer.rank == 8 %>
	        	    <div class="rank_eight">
		        	    <%= @engineer.rank %>
		        	</div>
		        <% elsif @engineer.rank == 7 %>
	        	    <div class="rank_seven">
		        	    <%= @engineer.rank %>
		        	</div>
		        <% elsif @engineer.rank == 6 %>
	        	    <div class="rank_six">
		        	    <%= @engineer.rank %>
		        	</div>
		        <% elsif @engineer.rank == 5 %>
	        	    <div class="rank_five">
		        	    <%= @engineer.rank %>
		        	</div>
		        <% elsif @engineer.rank == 4 %>
	        	    <div class="rank_four">
		        	    <%= @engineer.rank %>
		        	</div>
		        <% elsif @engineer.rank == 3 %>
	        	    <div class="rank_three">
		        	    <%= @engineer.rank %>
		        	</div>
		        <% elsif @engineer.rank == 2 %>
	        	    <div class="rank_two">
		        	    <%= @engineer.rank %>
		        	</div>
		        <% else %>
	        	    <div class="rank_one">
		        	    <%= @engineer.rank %>
		        	</div>
		        <% end %>
	        	<% if user_signed_in? %>
		 		    <% if @user = current_user %>
	        			<%= link_to evolution_path(current_user.id), method: :patch, 'data-toggle' => "tooltip", 'data-placement'=>"right", title:"称号の更新" do %>
	        			<i class="fas fa-upload info_created_at">Up grade</i>
	        			<% end %>
        		    <% end %>
	    		<% end %>

	        </th>
	    </tr>

        <tr>
	        <th class="info_created_at tag"><%= simple_format(@engineer.introduction) %></th>
	    </tr>

	    <% if user_signed_in? %>
		    <% if @user = current_user %>
			    <tr>
			        <th>
			        	<%= link_to edit_engineer_path(current_user.id) do %>
			        	<i class="fas fa-wrench info_created_at">編集する</i>
			        	<% end %>
			        </th>
			    </tr>
		    <% end %>
	    <% end %>

    </table>
  </div>


  <div class="col-md-9">
    <% if user_signed_in? && @engineer.id == current_user.id %>

		<div class='tabs'>
		  <div class='my-tab-buttons'>
		    <span class='my-content1'>記事</span>
		    <span class='my-content2'>スキル</span>
		    <span class='my-content3'>マーク</span>
		    <span class='my-content4'>オファー</span>
		    <span class='my-content5'>チャット</span>
		    <div id='my-lamp' class='my-content1'></div>
		  </div>
		  <div class='my-tab-content'>

		    <div class='my-content1'>
		    	<%= render 'users/infos/infos_search', infos: @infos %>
	        </div>

	        <div class='my-content2'>
				<%= render 'users/engineers/skill', languages: @languages %>
	        </div>

	        <div class='my-content3'>
	      	    <%= render 'users/marks/marks', marks: @marks %>
	        </div>
	        <div class='my-content4'>
	        	<%= render 'companies/offers/offers', offers: @offers %>
	        </div>
	        <div class='my-content5'>
	        	<%= render 'users/boxes/boxes', boxes: @boxes %>
	        </div>

	      </div>
		</div>

	<% else %>

	    <div class='tabs'>
		  <div class='tab-buttons'>
		    <span class='content1'>記事</span>
		    <span class='content2'>スキル</span>
		    <span class='content3'>マーク</span>
		    <div id='lamp' class='content1'></div>
		  </div>
		  <div class='tab-content'>

		    <div class='content1'>
		    	<%= render 'users/infos/infos', infos: @infos %>
	        </div>

	        <div class='content2'>
				<%= render 'users/engineers/skill', languages: @languages %>
	        </div>

	        <div class='content3'>
	        	<%= render 'users/marks/marks', marks: @marks %>
	        </div>
	      </div>
	    </div>

	<% end %>
</div>
</div>
</div>
</div>